'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Spinner } from '@/components/ui/spinner'
import { AlertCircle, Save, Send } from 'lucide-react'
import { Alert, AlertDescription } from '@/components/ui/alert'
import type { RequestType, Request } from '@/lib/types'

interface RequestFormProps {
  requestTypes: RequestType[]
  existingRequest?: Request
}

export function RequestForm({ requestTypes, existingRequest }: RequestFormProps) {
  const [formData, setFormData] = useState({
    request_type_id: existingRequest?.request_type_id || '',
    start_date: existingRequest?.start_date || '',
    end_date: existingRequest?.end_date || '',
    start_time: existingRequest?.start_time || '',
    end_time: existingRequest?.end_time || '',
    reason: existingRequest?.reason || '',
    observations: existingRequest?.observations || '',
  })
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [loadingAction, setLoadingAction] = useState<'save' | 'submit' | null>(null)
  const router = useRouter()
  const supabase = createClient()

  const selectedType = requestTypes.find(t => t.id === formData.request_type_id)

  const handleSave = async (submit: boolean = false) => {
    setError(null)
    setIsLoading(true)
    setLoadingAction(submit ? 'submit' : 'save')

    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('No autenticado')

      const requestData = {
        ...formData,
        user_id: user.id,
        status: submit ? 'ENVIADO' : 'BORRADOR',
        submitted_at: submit ? new Date().toISOString() : null,
        code: '', // Will be generated by trigger
      }

      if (existingRequest) {
        // Update existing request
        const { error: updateError } = await supabase
          .from('requests')
          .update({
            ...formData,
            status: submit ? 'ENVIADO' : existingRequest.status,
            submitted_at: submit ? new Date().toISOString() : existingRequest.submitted_at,
          })
          .eq('id', existingRequest.id)

        if (updateError) throw updateError
      } else {
        // Create new request
        const { error: insertError } = await supabase
          .from('requests')
          .insert(requestData)

        if (insertError) throw insertError
      }

      router.push('/dashboard/solicitudes')
      router.refresh()
    } catch (err) {
      console.error('Error saving request:', err)
      setError(err instanceof Error ? err.message : 'Error al guardar la solicitud')
    } finally {
      setIsLoading(false)
      setLoadingAction(null)
    }
  }

  const isValid = formData.request_type_id && formData.start_date && formData.end_date && formData.reason

  return (
    <Card>
      <CardHeader>
        <CardTitle>{existingRequest ? 'Editar Solicitud' : 'Datos de la Solicitud'}</CardTitle>
        <CardDescription>
          Completa todos los campos requeridos para tu solicitud
        </CardDescription>
      </CardHeader>
      <CardContent>
        <FieldGroup>
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <Field>
            <FieldLabel htmlFor="request_type_id">Tipo de Solicitud *</FieldLabel>
            <Select
              value={formData.request_type_id}
              onValueChange={(value) => setFormData({ ...formData, request_type_id: value })}
              disabled={isLoading}
            >
              <SelectTrigger>
                <SelectValue placeholder="Selecciona el tipo de solicitud" />
              </SelectTrigger>
              <SelectContent>
                {requestTypes.map((type) => (
                  <SelectItem key={type.id} value={type.id}>
                    {type.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {selectedType?.description && (
              <FieldDescription>{selectedType.description}</FieldDescription>
            )}
          </Field>

          <div className="grid gap-4 sm:grid-cols-2">
            <Field>
              <FieldLabel htmlFor="start_date">Fecha de Inicio *</FieldLabel>
              <Input
                id="start_date"
                type="date"
                value={formData.start_date}
                onChange={(e) => setFormData({ ...formData, start_date: e.target.value })}
                disabled={isLoading}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="end_date">Fecha de Fin *</FieldLabel>
              <Input
                id="end_date"
                type="date"
                value={formData.end_date}
                onChange={(e) => setFormData({ ...formData, end_date: e.target.value })}
                min={formData.start_date}
                disabled={isLoading}
              />
            </Field>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <Field>
              <FieldLabel htmlFor="start_time">Hora de Inicio (opcional)</FieldLabel>
              <Input
                id="start_time"
                type="time"
                value={formData.start_time}
                onChange={(e) => setFormData({ ...formData, start_time: e.target.value })}
                disabled={isLoading}
              />
            </Field>
            <Field>
              <FieldLabel htmlFor="end_time">Hora de Fin (opcional)</FieldLabel>
              <Input
                id="end_time"
                type="time"
                value={formData.end_time}
                onChange={(e) => setFormData({ ...formData, end_time: e.target.value })}
                disabled={isLoading}
              />
            </Field>
          </div>

          <Field>
            <FieldLabel htmlFor="reason">Motivo *</FieldLabel>
            <Textarea
              id="reason"
              placeholder="Describe el motivo de tu solicitud..."
              value={formData.reason}
              onChange={(e) => setFormData({ ...formData, reason: e.target.value })}
              disabled={isLoading}
              rows={4}
            />
            <FieldDescription>
              Explica detalladamente el motivo de tu solicitud de permiso o justificación
            </FieldDescription>
          </Field>

          <Field>
            <FieldLabel htmlFor="observations">Observaciones (opcional)</FieldLabel>
            <Textarea
              id="observations"
              placeholder="Información adicional..."
              value={formData.observations}
              onChange={(e) => setFormData({ ...formData, observations: e.target.value })}
              disabled={isLoading}
              rows={2}
            />
          </Field>

          {selectedType?.requires_attachment && (
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                Este tipo de solicitud requiere adjuntar documentos de respaldo.
                Podrás adjuntarlos después de guardar la solicitud.
              </AlertDescription>
            </Alert>
          )}
        </FieldGroup>
      </CardContent>
      <CardFooter className="flex flex-col sm:flex-row gap-3">
        <Button
          type="button"
          variant="outline"
          onClick={() => handleSave(false)}
          disabled={isLoading || !isValid}
          className="w-full sm:w-auto"
        >
          {loadingAction === 'save' ? <Spinner className="mr-2" /> : <Save className="mr-2 h-4 w-4" />}
          Guardar Borrador
        </Button>
        <Button
          type="button"
          onClick={() => handleSave(true)}
          disabled={isLoading || !isValid}
          className="w-full sm:w-auto"
        >
          {loadingAction === 'submit' ? <Spinner className="mr-2" /> : <Send className="mr-2 h-4 w-4" />}
          Enviar Solicitud
        </Button>
      </CardFooter>
    </Card>
  )
}
